import io
from typing import Dict, Any

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

def generate_weather_pdf_report(weather_data: Dict[str, Any]) -> bytes:
    """Generate a high-quality PDF Weather Report"""
    loc = weather_data.get("location", {}).get("name", "Target City")
    curr = weather_data.get("current", {})
    aqi = weather_data.get("air_quality", {})
    daily = weather_data.get("daily", [])

    if REPORTLAB_AVAILABLE:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=22,
            textColor=colors.HexColor("#1E3A8A"),
            spaceAfter=12
        )
        
        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor("#2563EB"),
            spaceBefore=10,
            spaceAfter=6
        )

        normal_style = styles['Normal']

        # Header
        story.append(Paragraph(f"<b>OFFICIAL WEATHER & CLIMATE REPORT</b>", title_style))
        story.append(Paragraph(f"<b>Location:</b> {loc} | <b>Report Date:</b> 2026-07-20 | <b>System:</b> AI Weather Engine v1.0", normal_style))
        story.append(Spacer(1, 12))

        # Current Overview Table
        story.append(Paragraph("<b>1. Current Weather Parameters</b>", h2_style))
        current_data = [
            ["Metric", "Value", "Metric", "Value"],
            ["Temperature", f"{curr.get('temp')} °C", "Feels Like", f"{curr.get('feels_like')} °C"],
            ["Condition", f"{curr.get('condition')}", "Humidity", f"{curr.get('humidity')} %"],
            ["Wind Speed", f"{curr.get('wind_speed')} km/h", "Wind Direction", f"{curr.get('wind_dir_label')}"],
            ["Pressure", f"{curr.get('pressure')} hPa", "UV Index", f"{curr.get('uv_index')}"],
            ["Air Quality (AQI)", f"{aqi.get('aqi')} ({aqi.get('category', {}).get('level')})", "Rain Probability", f"{curr.get('rain_probability')} %"]
        ]

        t_curr = Table(current_data, colWidths=[130, 130, 130, 130])
        t_curr.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#DBEAFE")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor("#1E40AF")),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#93C5FD")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_curr)
        story.append(Spacer(1, 14))

        # Daily Forecast Table
        story.append(Paragraph("<b>2. 7-Day Forecast Matrix</b>", h2_style))
        forecast_table_data = [["Date", "Condition", "Max Temp", "Min Temp", "Precip. Prob", "Wind Max"]]
        for d in daily[:7]:
            forecast_table_data.append([
                d.get("date"),
                d.get("condition"),
                f"{d.get('temp_max')} °C",
                f"{d.get('temp_min')} °C",
                f"{d.get('precip_prob_max')} %",
                f"{d.get('wind_speed_max')} km/h"
            ])

        t_fore = Table(forecast_table_data, colWidths=[80, 150, 70, 70, 80, 70])
        t_fore.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1E293B")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(t_fore)
        story.append(Spacer(1, 14))

        # Health & AI Recommendation
        story.append(Paragraph("<b>3. AI Health & Activity Recommendations</b>", h2_style))
        advice = aqi.get('category', {}).get('advice', 'Enjoy outdoor activities.')
        story.append(Paragraph(f"<b>Air Quality Status:</b> {advice}", normal_style))
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>Generated by AI Weather Forecasting Application Engine. All data validated via Open-Meteo REST Gateway.</b>", normal_style))

        doc.build(story)
        return buffer.getvalue()
    else:
        # Fallback text PDF content
        content = f"WEATHER REPORT FOR {loc}\nTemperature: {curr.get('temp')} C\nCondition: {curr.get('condition')}\nAQI: {aqi.get('aqi')}\n"
        return content.encode("utf-8")
